/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mini;

import com.email.durgesh.Email;
import java.awt.Component;
import java.awt.HeadlessException;
import java.sql.Array;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
class Otp 
{
      String OTP(int len) 
    { 
        int f =1 ; int x=0;
        Random ran = new Random(); 
  
        int[] otp = new int[6]; 
  
        for (int i = 0; i < 6 ; i++) 
        { 
            while(otp[i]==0)
            {
		otp[i] = ran.nextInt(10);
            }	
        }
        for (int i = 0; i < 6 ; i++) 
        { 
           x =  x + otp[i]*f;
           f= f*10;
        } 
	String s = Integer.toString(x);
        return s; 
    } 
    
    
}


public class Register extends javax.swing.JFrame {

  
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Name = new java.awt.TextField();
        middle_name = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        surname = new java.awt.TextField();
        jLabel5 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        schoolname = new java.awt.TextField();
        mar = new java.awt.Label();
        marks = new java.awt.Label();
        maths = new java.awt.Label();
        hindi = new java.awt.Label();
        hinSanSub = new java.awt.TextField();
        mathSub = new java.awt.TextField();
        science1 = new java.awt.Label();
        social_science = new java.awt.Label();
        ssSub = new java.awt.TextField();
        english = new java.awt.Label();
        engsub = new java.awt.TextField();
        next = new java.awt.Button();
        marSub = new java.awt.TextField();
        scisub = new java.awt.TextField();
        label2 = new java.awt.Label();
        percent1 = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        Phone_no = new java.awt.TextField();
        label4 = new java.awt.Label();
        address = new java.awt.TextField();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        password = new javax.swing.JPasswordField();
        confirpass = new javax.swing.JPasswordField();
        emailid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        verify = new java.awt.Button();
        send = new java.awt.Button();
        resend = new java.awt.Button();
        verotp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));

        button1.setBackground(new java.awt.Color(0, 0, 0));
        button1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 153, 0));
        button1.setLabel("back");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Register Your account");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Name");

        Name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        middle_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        middle_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middle_nameActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("name");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("middle name");

        surname.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("surname");

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 153, 0));
        label1.setText("School");

        schoolname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                schoolnameInputMethodTextChanged(evt);
            }
        });
        schoolname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolnameActionPerformed(evt);
            }
        });
        schoolname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                schoolnameKeyPressed(evt);
            }
        });

        mar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mar.setForeground(new java.awt.Color(255, 255, 255));
        mar.setText("Marathi");

        marks.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        marks.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        marks.setForeground(new java.awt.Color(255, 153, 0));
        marks.setText("Marks");

        maths.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        maths.setForeground(new java.awt.Color(255, 255, 255));
        maths.setText("maths");

        hindi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        hindi.setForeground(new java.awt.Color(255, 255, 255));
        hindi.setText("hindi/sanskrit");

        hinSanSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hinSanSubActionPerformed(evt);
            }
        });

        mathSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathSubActionPerformed(evt);
            }
        });

        science1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        science1.setForeground(new java.awt.Color(255, 255, 255));
        science1.setText("science");

        social_science.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        social_science.setForeground(new java.awt.Color(255, 255, 255));
        social_science.setText("social science");

        ssSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssSubActionPerformed(evt);
            }
        });

        english.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        english.setForeground(new java.awt.Color(255, 255, 255));
        english.setText("english");

        engsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engsubActionPerformed(evt);
            }
        });

        next.setBackground(new java.awt.Color(0, 0, 0));
        next.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        next.setForeground(new java.awt.Color(255, 153, 0));
        next.setLabel("Create account");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        marSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marSubActionPerformed(evt);
            }
        });

        scisub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scisubActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 153, 51));
        label2.setText("% Marks");

        percent1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        percent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percent1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 51));
        jLabel6.setText("Username");

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        label3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 153, 0));
        label3.setText("Phone no");

        Phone_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phone_noActionPerformed(evt);
            }
        });

        label4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 153, 0));
        label4.setName("Address"); // NOI18N
        label4.setText("Address");

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });

        label5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 153, 0));
        label5.setText("Enter password");

        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 153, 0));
        label6.setText("Confirm Password");

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });

        confirpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirpassActionPerformed(evt);
            }
        });

        emailid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailidActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Email");
        jLabel7.setToolTipText("");

        verify.setBackground(new java.awt.Color(0, 0, 0));
        verify.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        verify.setForeground(new java.awt.Color(255, 153, 0));
        verify.setLabel("verify");
        verify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyActionPerformed(evt);
            }
        });

        send.setBackground(new java.awt.Color(0, 0, 0));
        send.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        send.setForeground(new java.awt.Color(255, 153, 0));
        send.setLabel("send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        resend.setBackground(new java.awt.Color(0, 0, 0));
        resend.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        resend.setForeground(new java.awt.Color(255, 153, 0));
        resend.setLabel("resend");
        resend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resendActionPerformed(evt);
            }
        });

        verotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verotpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(151, 151, 151)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(105, 105, 105)
                                                .addComponent(middle_name, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(85, 85, 85)
                                                .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(schoolname, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(201, 201, 201)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(maths, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(social_science, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(mar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mathSub, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(marSub, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ssSub, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(59, 59, 59)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(science1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(english, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hindi, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(engsub, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(scisub, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hinSanSub, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(percent1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(marks, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(179, 914, Short.MAX_VALUE)))))
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(223, 223, 223)
                            .addComponent(jLabel4)
                            .addGap(183, 183, 183)
                            .addComponent(jLabel5)
                            .addGap(221, 221, 221))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(Phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(19, 19, 19)
                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(emailid, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(verify, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(verotp, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29)
                        .addComponent(resend, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(confirpass, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(middle_name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(surname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(schoolname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hindi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hinSanSub, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(marSub, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(mathSub, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(scisub, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(science1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(marks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(maths, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(percent1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ssSub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(social_science, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(english, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(engsub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Phone_no, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(verify, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(send, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confirpass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(verotp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        social_science.getAccessibleContext().setAccessibleName("science");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String otp1 ;

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MainFrame gotomain = new MainFrame();
        gotomain.setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
        JFrame g; 
        g = new JFrame();
        
        String t = Name.getText();
        if(2 < t.length())
        {
            Name.setText(t);
           
            
        }
        else 
        {
            this.setVisible(false) ;
            JOptionPane.showMessageDialog(g,   "name  is too short. Enter name again.");
             Name.setText("");
            this.setVisible(true) ;
        }
    }//GEN-LAST:event_NameActionPerformed

    private void engsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engsubActionPerformed
        // TODO add your handling code here:
          JFrame g; 
        g = new JFrame();
        String t = engsub.getText() ;
        try {
        int m = Integer.parseInt(t);
                if( m < 101 )
                {
                    engsub.setText(t);
                }
                else
                {
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(g,   " marks should be less than or eqals to 100 ");
                    this.setVisible(true);
                    engsub.setText("");
                }
                    
        }
        catch( Exception e )
        {
            this.setVisible(false);
              JOptionPane.showMessageDialog(g,   "Enter numbers only ");
              this.setVisible(true);
              engsub.setText("");
        }
    }//GEN-LAST:event_engsubActionPerformed
MainFrame gotomain1 = new MainFrame();

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        JFrame j = new JFrame();
      
        if( !"".equals(username.getText()) && !"".equals(Name.getText())  && !"".equals(middle_name.getText()) && !"".equals(surname.getText()) && !"".equals(schoolname.getText()) && !"".equals(marSub.getText())  && !"".equals(hinSanSub.getText())  && !"".equals(mathSub.getText())  && !"".equals(scisub.getText())  && !"".equals(ssSub.getText())  && !"".equals(engsub.getText())  && !"".equals(percent1.getText())  ){
        
            Connection con1 = null  ;
       PreparedStatement pst ;
       ResultSet rs = null ;
            try {  
                
              String email1 = "'"+emailid.getText()+"'"   ;  
              String user = ",'"+username.getText() +"'" ;
               String pass = ",'"+password.getText()+"'" ;
              String name = ",'"+  Name.getText() +"'"  ; 
              String middle_name1 = ",'"+ middle_name.getText() +"'"  ;
              String surname1 =",'"+  surname.getText() +"'"  ;
              String address1 = ",'"+address.getText()+"'"   ;
              String schoolname1 =",'"+ schoolname.getText()+"'";
              String phoneno = ",'"+Phone_no.getText()+"'" ;
              String hinsan1 = ",'"+ hinSanSub.getText() +"'" ;
              String marsub1 =",'"+ marSub.getText()+"'";
              String eng1 =",'"+ engsub.getText()+"'" ;
              String math1 =",'"+ mathSub.getText()  +"'"  ;
              String sci1 = ",'"+ scisub.getText()+"'" ;
              String sssub1 = ",'"+  ssSub.getText()+"'"  ;
              
              String m2 = email1 + user + pass + name + middle_name1 + surname1 + address1 + schoolname1 + phoneno + hinsan1 + marsub1 + eng1 + math1 + sci1 + sssub1 ;
              
              
              
                Class.forName("com.mysql.jdbc.Driver") ;
                con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/mini" ,"root","" );
                
                String n = "INSERT INTO student(email, username, password, name , midname, surname, address, schoolname, phoneno, hindi, marathi, english, maths, science, socialscience) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,? )" ;
                
                
                String m = "INSERT INTO `student` (`email`, `username`, `password`, `name`, `midname`, `surname`, `address`, `schoolname`, `phoneno`, `hindi`, `marathi`, `english`, `maths`, `science`, `socialscience`) VALUES ('rahulkishorgaikwad@gmail.com', 'fvcvcv', 'Asd@1310', 'Rahul', 'Kishor', 'Gaikwad', 'qwehdj jkfopj jflkpklf flkdfk fedf ', 'bakl vikas vidya mandir', '9702816011', '95', '95', '97', '100', '100', '100')" ;
                
                String m1 = "INSERT INTO `student` (`email`, `username`, `password`, `name`, `midname`, `surname`, `address`, `schoolname`, `phoneno`, `hindi`, `marathi`, `english`, `maths`, `science`, `socialscience`) VALUES ("+ m2 + ")" ;
                
                pst = con1.prepareStatement(m1);
                
                        
                /*pst.setString(0,email ) ;
                pst.setString(1,user );
                pst.setString(2,pass   );
                pst.setString(3,name );
                pst.setString(4, middle_name1 );
                pst.setString(5,  surname1 );
                pst.setString(6,  address1 );
                pst.setString(7, schoolname1 );
                pst.setString(8, phoneno  );
                pst.setString(9, hinsan1  );
                pst.setString(10, marsub1 );
                pst.setString(11, eng1);
                pst.setString(12,math1 );
                pst.setString(13,sci1);
                pst.setString(14,sssub1); */
                
                
               
                boolean nwe  =  pst.execute() ;
               
                
                
                if(nwe)
                {
                    JOptionPane.showMessageDialog( j, "username and password matches") ;
                    this.setVisible(false);
                    int a = JOptionPane.showConfirmDialog(j, "Are you sure");
           
            if( a == JOptionPane.YES_OPTION ) {
                
                this.setVisible(false);
                
                gotomain1.setVisible(true);
            }
            
                }
                
               
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }

        
            int a ;this.setVisible(false);
            a = JOptionPane.showConfirmDialog(j, " are you sure. ");
            
            if(a == JOptionPane.YES_OPTION)
            {
                
               gotomain1.setVisible(true);
            }
            else
            {
                this.setVisible(true);
            }
            
        }
        else{
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(j , " Filled all the blocks ");
                    this.setVisible(true);
                    }
    }//GEN-LAST:event_nextActionPerformed

    private void schoolnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolnameActionPerformed
        // TODO add your handling code here:
       JFrame g; 
        g = new JFrame();
        
        String t = schoolname.getText();
        if(10 < t.length())
        {
            schoolname.setText(t) ;    
        }
        else 
        {
            this.setVisible(false) ;
            JOptionPane.showMessageDialog(g,   "address  is too short. Enter name again.");
             schoolname.setText("");
            this.setVisible(true) ;
        }
    }//GEN-LAST:event_schoolnameActionPerformed

    private void schoolnameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_schoolnameInputMethodTextChanged
        // TODO add your handling code here:
      
    }//GEN-LAST:event_schoolnameInputMethodTextChanged

    private void schoolnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_schoolnameKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_schoolnameKeyPressed

    private void scisubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scisubActionPerformed
        // TODO add your handling code here:
          JFrame g; 
        g = new JFrame();
        String t = scisub.getText() ;
        try {
        int m = Integer.parseInt(t);
                if( m < 101 )
                {
                    scisub.setText(t);
                }
                else
                {
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(g,   " marks should be less than or eqals to 100 ");
                    this.setVisible(true);
                    scisub.setText("");
                }
                    
        }
        catch( Exception e )
        {
            this.setVisible(false);
              JOptionPane.showMessageDialog(g,   "Enter numbers only ");
              this.setVisible(true);
              scisub.setText("");
        }
    }//GEN-LAST:event_scisubActionPerformed

    private void mathSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathSubActionPerformed
        // TODO add your handling code here:
         JFrame g; 
        g = new JFrame();
        String t = mathSub.getText() ;
        try {
        int m = Integer.parseInt(t);
                if( m < 101 )
                {
                    mathSub.setText(t);
                }
                else
                {
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(g,   " marks should be less than or eqals to 100 ");
                    this.setVisible(true);
                    mathSub.setText("");
                }
                    
        }
        catch( Exception e )
        {
            this.setVisible(false);
              JOptionPane.showMessageDialog(g,   "Enter numbers only ");
              this.setVisible(true);
              mathSub.setText("");
        }
    }//GEN-LAST:event_mathSubActionPerformed

    private void middle_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middle_nameActionPerformed
        // TODO add your handling code here:
       JFrame g; 
        g = new JFrame();
        
        String t = middle_name.getText();
        if(2 < t.length())
        {
            middle_name.setText(t);
           
            
        }
        else 
        {
            this.setVisible(false) ;
            JOptionPane.showMessageDialog(g,   "middle name is too short. Enter name again.");
            middle_name.setText("");
            this.setVisible(true) ;
        }
    }//GEN-LAST:event_middle_nameActionPerformed

    private void surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameActionPerformed
        // TODO add your handling code here:
        JFrame g; 
        g = new JFrame();
        
        String t = surname.getText();
        if(2 < t.length())
        {
            surname.setText(t);
           
            
        }
        else 
        {
            this.setVisible(false) ;
            JOptionPane.showMessageDialog(g,   "surname is too short. Enter name again.");
            surname.setText("");
            this.setVisible(true) ;
        }
    }//GEN-LAST:event_surnameActionPerformed

    private void marSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marSubActionPerformed
        // TODO add your handling code here:
         JFrame g; 
        g = new JFrame();
        String t = marSub.getText() ;
        try {
        int m = Integer.parseInt(t);
                if( m < 101 )
                {
                    marSub.setText(t);
                }
                else
                {
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(g,   " marks should be less than or eqals to 100 ");
                    this.setVisible(true);
                    marSub.setText("");
                }
                    
        }
        catch( Exception e )
        {
            this.setVisible(false);
              JOptionPane.showMessageDialog(g,   "Enter numbers only ");
              this.setVisible(true);
              marSub.setText("");
        }
    }//GEN-LAST:event_marSubActionPerformed

    private void hinSanSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hinSanSubActionPerformed
        // TODO add your handling code here:
         JFrame g; 
        g = new JFrame();
        String t = hinSanSub.getText() ;
        try {
        int m = Integer.parseInt(t);
                if( m < 101 )
                {
                    hinSanSub.setText(t);
                }
                else
                {
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(g,   " marks should be less than or eqals to 100 ");
                    this.setVisible(true);
                    hinSanSub.setText("");
                }
                    
        }
        catch( Exception e )
        {
            this.setVisible(false);
              JOptionPane.showMessageDialog(g,   "Enter numbers only ");
              this.setVisible(true);
              hinSanSub.setText("");
        }
    }//GEN-LAST:event_hinSanSubActionPerformed

    private void ssSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssSubActionPerformed
        // TODO add your handling code here:
         JFrame g; 
        g = new JFrame();
        String t = ssSub.getText() ;
        try {
        int m = Integer.parseInt(t);
                if( m < 101 )
                {
                    ssSub.setText(t);
                }
                else
                {
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(g,   " marks should be less than or eqals to 100 ");
                    this.setVisible(true);
                    ssSub.setText("");
                }
                    
        }
        catch( Exception e )
        {
            this.setVisible(false);
              JOptionPane.showMessageDialog(g,   "Enter numbers only ");
              this.setVisible(true);
              ssSub.setText("");
        }
    }//GEN-LAST:event_ssSubActionPerformed

    private void percent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percent1ActionPerformed
        // TODO add your handling code here:
        JFrame g = new JFrame() ;
         try
       {
           int m1 = Integer.parseInt(marSub.getText());
           int m2 = Integer.parseInt(hinSanSub.getText());
           int m3 = Integer.parseInt(mathSub.getText());
           int m4 = Integer.parseInt(scisub.getText());
           int m5 = Integer.parseInt(ssSub.getText());
           int m6 = Integer.parseInt(engsub.getText());
           float avg = (float) ( m1+m2+m3+m4+m5+m6)/6;
           String t = String.valueOf(avg) ;
           percent1.setText(t);
       }
       catch( Exception e )
       {
           this.setVisible(false);
              JOptionPane.showMessageDialog(g,   " Filled Marks first");
              this.setVisible(true);
              percent1.setText("");
       }
    }//GEN-LAST:event_percent1ActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void Phone_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phone_noActionPerformed
        // TODO add your handling code here:
        JFrame g;
        g = new JFrame();
        String t = Phone_no.getText() ;
        try {
            int m = Integer.parseInt(t);
            if( t.length() == 10 )
            {

                Phone_no.setText(t);
            }
            else
            {
                this.setVisible(false);
                JOptionPane.showMessageDialog(g,   " no is always 10 digital  ");
                this.setVisible(true);
                Phone_no.setText("");
            }

        }
        catch( Exception e )
        {
            this.setVisible(false);
            JOptionPane.showMessageDialog(g,   "Enter numbers only ");
            this.setVisible(true);
            Phone_no.setText("");
        }
    }//GEN-LAST:event_Phone_noActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
        JFrame g;
        g = new JFrame();

        String t = address.getText();
        if(10 < t.length())
        {
            address.setText(t);
        }
        else
        {
            this.setVisible(false) ;
            JOptionPane.showMessageDialog(g,   "Address is too short. Enter name again.");
            address.setText("");
            this.setVisible(true) ;
        }
    }//GEN-LAST:event_addressActionPerformed
    public static boolean isValid(String password) 
    { 
        if (!((password.length() >= 8) 
              && (password.length() <= 15))) { 
            return false; 
        } 
        if (password.contains(" ")) { 
            return false; 
        } 
        if (true) { 
            int count = 0; 
            for (int i = 0; i <= 9; i++) { 
  
                String str1 = Integer.toString(i); 
  
                if (password.contains(str1)) { 
                    count = 1; 
                } 
            } 
            if (count == 0) { 
                return false; 
            } 
        } 
  
        if (!(password.contains("@") || password.contains("#") 
              || password.contains("!") || password.contains("~") 
              || password.contains("$") || password.contains("%") 
              || password.contains("^") || password.contains("&") 
              || password.contains("*") || password.contains("(") 
              || password.contains(")") || password.contains("-") 
              || password.contains("+") || password.contains("/") 
              || password.contains(":") || password.contains(".") 
              || password.contains(", ") || password.contains("<") 
              || password.contains(">") || password.contains("?") 
              || password.contains("|"))) { 
            return false; 
        } 
  
        if (true) { 
            int count = 0; 
            
            for (int i = 65; i <= 90; i++) { 
  
                // type casting 
                char c = (char)i; 
  
                String str1 = Character.toString(c); 
                if (password.contains(str1)) { 
                    count = 1; 
                } 
            } 
            if (count == 0) { 
                return false; 
            } 
        } 
  
        if (true) { 
            int count = 0; 
  
            for (int i = 90; i <= 122; i++) { 
   
                char c = (char)i; 
                String str1 = Character.toString(c); 
  
                if (password.contains(str1)) { 
                    count = 1; 
                } 
            } 
            if (count == 0) { 
                return false; 
            } 
        } 
        return true; 
    } 
  
    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        JFrame g; 
        g = new JFrame();
        
        String t = password.getText();
        if( isValid(t))
        {
            password.setText(t);   
        }
        else 
        {
            this.setVisible(false) ;
            JOptionPane.showMessageDialog(g,   "Password contain at least one digit and one character and special character having length between 8 to 15");
             password.setText("");
            this.setVisible(true) ;
        }
    }//GEN-LAST:event_passwordActionPerformed

    private void confirpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirpassActionPerformed
        // TODO add your handling code here:
        JFrame g; 
        g = new JFrame();
        
        String t = confirpass.getText();
        if( t.equals(password.getText()) )
        {
            confirpass.setText(t);   
        }
        else 
        {
            this.setVisible(false) ;
            JOptionPane.showMessageDialog(g,   "Please enter same password");
             confirpass.setText("");
            this.setVisible(true) ;
        }
    }//GEN-LAST:event_confirpassActionPerformed

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_passwordKeyTyped

    private void emailidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailidActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_emailidActionPerformed
boolean flag = false ;
    private void verifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyActionPerformed
   JFrame j = new JFrame();
   
        if( verotp.getText().equals(o22) )
        {
                this.setVisible(false);
                JOptionPane.showMessageDialog(j, "otp verified.");
                this.setVisible(true);
                flag = true ;
        }   
        else
        {
            this.setVisible(false);
            JOptionPane.showMessageDialog(j, "otp is not valid click on resen");
            this.setVisible(true);
        }
         
    
      
    }//GEN-LAST:event_verifyActionPerformed
String o22 ;
    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
 JFrame j = new JFrame();
         try
     {
         Otp o11 = new Otp();
         o22 = o11.OTP(6) ;
         Email email = new Email("rahulkishorgaikwad@gmail.com" , "rahul2001");
         email.setFrom("rahulkishorgaikwad@gmail.com", "Rahul Gaikwad");
         email.setSubject("kljafj");
         
         email.setContent("<h1>otp is "+o22+" </h1>", "text/html");
         email.addRecipient(emailid.getText());
         email.send();
         this.setVisible(false);
         JOptionPane.showMessageDialog(j, o22);
         this.setVisible(true);
     }
     catch(Exception e)
     {
         
     }
    }//GEN-LAST:event_sendActionPerformed

    private void resendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resendActionPerformed
        // TODO add your handling code here:
          try
     {
         Otp o11 = new Otp();
         otp1 = o11.OTP(6) ;
         Email email = new Email("rahulkishorgaikwad@gmail.com" , "rahul2001");
         email.setFrom("rahulkishorgaikwad@gmail.com", "Rahul Gaikwad");
         email.setSubject("Career management system ");
         
         email.setContent("<h1>otp is "+otp1+" </h1>", "text/html");
         email.addRecipient(emailid.getText());
         email.send();
     }
     catch(Exception e)
     {
         
     }
    }//GEN-LAST:event_resendActionPerformed

    private void verotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verotpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verotpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Name;
    private java.awt.TextField Phone_no;
    private java.awt.TextField address;
    private java.awt.Button button1;
    private javax.swing.JPasswordField confirpass;
    private javax.swing.JTextField emailid;
    private java.awt.Label english;
    private java.awt.TextField engsub;
    private java.awt.TextField hinSanSub;
    private java.awt.Label hindi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label mar;
    private java.awt.TextField marSub;
    private java.awt.Label marks;
    private java.awt.TextField mathSub;
    private java.awt.Label maths;
    private java.awt.TextField middle_name;
    private java.awt.Button next;
    private javax.swing.JPasswordField password;
    private java.awt.TextField percent1;
    private java.awt.Button resend;
    private java.awt.TextField schoolname;
    private java.awt.Label science1;
    private java.awt.TextField scisub;
    private java.awt.Button send;
    private java.awt.Label social_science;
    private java.awt.TextField ssSub;
    private java.awt.TextField surname;
    private javax.swing.JTextField username;
    private java.awt.Button verify;
    private javax.swing.JTextField verotp;
    // End of variables declaration//GEN-END:variables
}
